apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: territorial-aardwolf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: territorial-aardwolf-python 
  name: territorial-aardwolf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: territorial-aardwolf-python 
